const Pool = require('pg').Pool;
const pool = new Pool({
    user: "postgres",
    password: "1234",
    database: "wadhw4",
    host: "localhost",
    port: "5432"
});

const execute = async(query) => {
    try {
        await pool.connect(); // gets connection
        await pool.query(query); // sends queries
        return true;
    } catch (error) {
        console.error(error.stack);
        return false;
    }
};

// A simple query that creates a table in our database
// Note that the "SERIAL"  pseudo-type that is used after the "id" is used to create a sequence object,
// and set the next value generated by the sequence as the default value for the column
const createPostTblQuery = `
    CREATE TABLE IF NOT EXISTS "posttable" (
	    "id" SERIAL PRIMARY KEY,         
	    "title" VARCHAR(200) NOT NULL,
	    "body" VARCHAR(200) NOT NULL,
        "date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP  
    );`;

const createUsersTblQuery = `
    CREATE TABLE IF NOT EXISTS "users" (
        "id" SERIAL PRIMARY KEY,
        "email" VARCHAR(200) UNIQUE NOT NULL,
        "password" VARCHAR(200) NOT NULL
    );`;

// A function to execute the previous query   
execute(createPostTblQuery).then(result => {
    if (result) {
        console.log('If does not exists, create the "posttable" table');
    }
});

execute(createUsersTblQuery).then(result => {
    if (result) {
        console.log('If does not exists, create the "users" table');
    }
})

module.exports = pool;